version: "2"
services:
  nginx:
    volumes:
      - "./nginx/qa.conf:/etc/nginx/conf.d/default.conf"
  node:
    environment:
      - NODE_ENV=qa

  front:
    environment:
      - NODE_ENV=qa

  front-admin:
    environment:
      - NODE_ENV=qa
