version: "2"
services:
  nginx:
    volumes:
      - "./nginx/dev.conf:/etc/nginx/conf.d/default.conf"
      - "./front:/home/front"

  node:
    environment:
      - NODE_ENV=development

  front:
    environment:
      - NODE_ENV=development

  front-admin:
    environment:
      - NODE_ENV=development

  db:
    ports:
      - "5432:5432"
