version: "2"
services:
  node:
    build:
      context: .
      dockerfile: dockerfile_back
    volumes:
      - "./back:/home/back"
    depends_on:
      - "db"
    environment:
      - TZ=Europe/Paris
      - DATABASE_URL=postgres://test-user:test-pass@db:5432/test-db
      - COOKIE_SECRET=IAmSoSecret
      - SENTRY_ENV=test
      - TOKEN_HOST=http://localhost
      - EMAIL_KEY=key
      - EMAIL_KEY_SECRET=big_secret
      - SLACK_WEBHOOK_SU_ZEN_TECH=http://localhost
      - API_HOST=https://api-r.es-qvr.fr

  front:
    build:
      context: .
      dockerfile: dockerfile_front
    volumes:
      - "./front:/home/front"

  db:
    image: postgres
    environment:
      - POSTGRES_DB=test-db
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=test-pass
